#!/usr/bin/env python3
"""
scan_repo.py — turn a codebase into a half-filled evidence pack.

THIS IS NOT AN AUDIT AND IT DOES NOT PRODUCE ONE. It reads a repository, finds
the things a machine can honestly find, and writes an evidence pack with those
rows filled in and every remaining row marked NOT ESTABLISHED.

The point is the second half. Article 50 turns on facts that are not in any
codebase — whether you are the provider or the deployer, whether the system is
available in the Union, the date it was placed on the market, whether you hold a
law-enforcement authorisation. A scanner that guessed those would be inventing
the inputs to a compliance verdict, which is the failure this whole repository
exists to prevent. So it refuses, loudly, in the file it writes.

What it can genuinely tell you: whether the codebase talks to a model provider,
which output modalities it generates, whether anything in it marks output as
synthetic, and where the strings that look like AI disclosures live.

Usage:
    python3 tools/scan_repo.py /path/to/your/product
    python3 tools/scan_repo.py /path/to/your/product --out ./my-audit
"""

from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path

SKIP_DIRS = {
    ".git", ".claude", "node_modules", "vendor", "dist", "build", ".next", "out", "target",
    "__pycache__", ".venv", "venv", ".tox", "coverage", ".cache", ".turbo",
    "site-packages", ".mypy_cache", ".pytest_cache", "Pods", ".gradle",
}
TEXT_EXT = {
    ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".py", ".rb", ".go", ".rs",
    ".java", ".kt", ".swift", ".php", ".cs", ".json", ".yaml", ".yml", ".toml",
    ".md", ".mdx", ".txt", ".html", ".vue", ".svelte", ".astro", ".env.example",
}
MAX_BYTES = 400_000

# (label, regex, what it evidences) — deliberately broad; a false positive costs
# the reader ten seconds, a false negative costs them an obligation.
SIGNALS: list[tuple[str, str, str]] = [
    ("model_provider", r"\b(anthropic|openai|@anthropic-ai|@google/generative-ai|google\.generativeai|cohere|mistralai|ollama|langchain|llama_?index|replicate|huggingface|together\.ai|groq|bedrock-runtime|vertexai|@ai-sdk)\b", "the codebase calls a model provider"),
    ("text_generation", r"(chat\.completions|messages\.create|generate_?content|createChatCompletion|streamText|generateText|\bcompletion\()", "generates text"),
    ("image_generation", r"\b(dall-?e|images\.generate|stable[- _]?diffusion|stability\.ai|midjourney|\bflux\b|imagen|text-to-image)\b", "generates images"),
    ("audio_generation", r"\b(elevenlabs|audio\.speech|text-to-speech|\btts\b|playht|play\.ht|resemble\.ai|voice[- _]?clon)", "generates or clones audio"),
    ("video_generation", r"\b(runwayml|pika\.art|sora|veo-\d|lumalabs|text-to-video)\b", "generates video"),
    ("provenance_marking", r"\b(c2pa|contentcredentials|content_credentials|digitalSourceType|trainedAlgorithmicMedia|iptc|synthid|watermark|steganograph)\b", "marks output provenance — Article 50(2) evidence"),
    ("emotion_biometric", r"\b(emotion[- _]?(recognition|detection)|face[- _]?api|faceapi|deepface|rekognition|biometric|facial[- _]?recognition|affect(ive)?[- _]?comput)\b", "may engage Article 50(3)"),
    ("sentiment_only", r"\bsentiment[- _]?(analysis|score|classif)", "sentiment — usually NOT Article 3(39) emotion recognition"),
    ("eu_signal", r"\b(gdpr|dsgvo|rgpd|eur\b|europe|\beu\b|impressum|cookie[- _]?consent)\b", "suggests EU exposure — not proof"),
]

DISCLOSURE = re.compile(
    r"(you (are|'re) (chatting|talking|speaking) with an ai"
    r"|i(')?m an ai|i am an ai|this is an ai"
    r"|ai[- ]generated|generated by ai|made with ai|created with ai"
    r"|powered by ai|ai assistant|ai agent|autonomous ai"
    r"|not a human|automated (system|assistant)"
    r"|artificially generated|synthetic (content|media))",
    re.I,
)
POLICY_FILE = re.compile(r"(privacy|terms|tos|legal|imprint|impressum|cookie|disclosure|colophon)", re.I)


def walk(root: Path):
    for p in root.rglob("*"):
        if p.is_dir():
            continue
        if any(part in SKIP_DIRS for part in p.parts):
            continue
        if p.suffix.lower() not in TEXT_EXT and p.name not in ("package.json", "requirements.txt", "Gemfile", "go.mod"):
            continue
        try:
            if p.stat().st_size > MAX_BYTES:
                continue
            yield p, p.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue


def first_commit(root: Path) -> str | None:
    try:
        out = subprocess.run(
            ["git", "-C", str(root), "log", "--reverse", "--format=%as", "--max-parents=0"],
            capture_output=True, text=True, timeout=20,
        )
        line = out.stdout.strip().splitlines()
        return line[0] if line else None
    except (OSError, subprocess.SubprocessError):
        return None


def scan(root: Path):
    hits: dict[str, list[tuple[str, int, str]]] = {k: [] for k, _, _ in SIGNALS}
    disclosures: list[tuple[str, int, str]] = []
    policies: list[str] = []
    compiled = [(k, re.compile(rx, re.I)) for k, rx, _ in SIGNALS]
    n_files = 0

    for path, text in walk(root):
        n_files += 1
        rel = str(path.relative_to(root))
        if POLICY_FILE.search(rel):
            policies.append(rel)
        for i, line in enumerate(text.splitlines(), 1):
            if len(line) > 600:
                line = line[:600]
            for key, rx in compiled:
                if len(hits[key]) < 12 and rx.search(line):
                    hits[key].append((rel, i, line.strip()[:180]))
            if len(disclosures) < 40 and DISCLOSURE.search(line):
                disclosures.append((rel, i, line.strip()[:180]))
    return hits, disclosures, sorted(set(policies))[:25], n_files


def cite(rows, limit=6) -> str:
    if not rows:
        return "_nothing found_"
    out = []
    for rel, ln, snippet in rows[:limit]:
        out.append(f"- `{rel}:{ln}` — `{snippet}`")
    if len(rows) > limit:
        out.append(f"- _…and {len(rows) - limit} more_")
    return "\n".join(out)


def yes_no(rows) -> str:
    return "**Signals found** — see below" if rows else "No signal found in the codebase"


UNKNOWN = "**NOT ESTABLISHED — you must answer this.**"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("repo", type=Path)
    ap.add_argument("--out", type=Path, default=Path("./audit-workspace"))
    args = ap.parse_args()

    root = args.repo.resolve()
    if not root.is_dir():
        raise SystemExit(f"{root} is not a directory")

    hits, disclosures, policies, n_files = scan(root)
    born = first_commit(root)
    pack = (args.out / "evidence-pack").resolve()
    (pack / "first-interaction").mkdir(parents=True, exist_ok=True)
    (pack / "outputs").mkdir(parents=True, exist_ok=True)
    (pack / "documents").mkdir(parents=True, exist_ok=True)

    modalities = [
        ("text", hits["text_generation"]), ("image", hits["image_generation"]),
        ("audio", hits["audio_generation"]), ("video", hits["video_generation"]),
    ]
    found_mod = [m for m, h in modalities if h]
    mod_line = (
        "**Signals found for: " + ", ".join(found_mod) + ".** Confirm and complete — "
        "a scanner sees calls, not what you ship."
        if found_mod else
        f"{UNKNOWN} No generation call matched. That may mean you generate nothing, "
        "or that you call a model in a way this scanner does not recognise."
    )

    date_line = (
        f"{UNKNOWN} First commit in this repository is **{born}**, which is a hint and "
        f"nothing more — it is not the date the system was placed on the market or put "
        f"into service, and that date decides whether Article 111(4) gives you until "
        f"2 December 2026 for Article 50(2)."
        if born else
        f"{UNKNOWN} This decides whether Article 111(4) gives you until 2 December 2026 "
        f"for the Article 50(2) marking duty."
    )

    (pack / "system-facts.md").write_text(f"""# System facts — {root.name}

> Half of this file was written by `tools/scan_repo.py` from the codebase at
> `{root}` ({n_files} files read). **The other half it refused to write.**
>
> Rows marked NOT ESTABLISHED turn on facts that are not in any codebase. If you
> leave them, the auditor will return `INSUFFICIENT_EVIDENCE` for every
> obligation that depends on them — which is the correct outcome, and more useful
> than a verdict built on a guess.

| Question | Answer |
|---|---|
| Legal entity | {UNKNOWN} |
| Product | {root.name} |
| **Provider, deployer, or both?** | {UNKNOWN} Provider = you develop the system and place it on the market or put it into service under your own name, including **for your own use** (Art. 3(3) and 3(11)). Deployer = you use it under your authority. Many operators are both. 50(1) and 50(2) bind providers; 50(3) and 50(4) bind deployers, so this row decides half the report. |
| **Output modalities generated** | {mod_line} |
| Available to persons in the EU? | {UNKNOWN} {"The codebase carries EU-related strings, which is a hint, not an answer." if hits["eu_signal"] else ""} |
| **Date placed on the market / put into service** | {date_line} |
| Emotion recognition present? | {yes_no(hits["emotion_biometric"])}. Test against Art. 3(39), not against your internal vocabulary. |
| Biometric categorisation present? | {yes_no(hits["emotion_biometric"])}. Test against Art. 3(40). |
| Deep fakes generated? | {UNKNOWN} Art. 3(60): content resembling real persons, objects, places, entities or events that would falsely appear authentic. |
| Is generated text published to inform the public on matters of public interest? | {UNKNOWN} Both limbs required — published, **and** informing the public on a matter of public interest. A blog on your industry usually qualifies; a support reply does not. |
| If yes: human review, and who holds editorial responsibility? | {UNKNOWN} The Art. 50(4) exemption needs both limbs. Name the natural or legal person. |
| Law-enforcement authorisation claimed? | {UNKNOWN} |
| SME / SMC? | {UNKNOWN} Reverses the direction of the penalty cap — Art. 99(6) and 99(6a). |
| **Marking technique used for synthetic output** | {"**Provenance signals found in the codebase** — listed below. Confirm what actually reaches the output, and prove it with a metadata dump in `outputs/`." if hits["provenance_marking"] else "**No provenance marking found anywhere in the codebase.** If that is right, Article 50(2) is very likely FAIL. Prove it either way with a metadata dump in `outputs/` — source code is not evidence of what the output carries."} |

---

## What the scanner found

### Model provider calls
{cite(hits["model_provider"])}

### Generation calls by modality
**Text**
{cite(hits["text_generation"], 4)}

**Image**
{cite(hits["image_generation"], 4)}

**Audio**
{cite(hits["audio_generation"], 4)}

**Video**
{cite(hits["video_generation"], 4)}

### Provenance / marking — Article 50(2)
{cite(hits["provenance_marking"], 8)}

### Emotion recognition or biometric categorisation — Article 50(3)
{cite(hits["emotion_biometric"], 6)}

Sentiment analysis, if any, listed separately because it is usually **not**
an emotion recognition system within Article 3(39):

{cite(hits["sentiment_only"], 4)}

### EU exposure hints — not proof
{cite(hits["eu_signal"], 4)}
""", encoding="utf-8")

    (pack / "first-interaction" / "candidates.md").write_text(f"""# Candidate disclosure strings

Strings in the codebase that look like AI disclosures, with where they live.

**These are candidates, not evidence.** Article 50(5) asks whether the
information reaches the person clearly and distinguishably **at the latest at the
time of the first interaction or exposure**. A string existing in a repository
says nothing about that. Replace this file with what a user actually meets first:
the opening message, the landing copy above the fold, the voice script, the
byline — captured as rendered text or HTML, in order.

If nothing below appears at the point of first interaction, say so. "No statement
at this surface that the output is AI-generated" is evidence, and it is often the
finding.

{cite(disclosures, 40)}
""", encoding="utf-8")

    (pack / "outputs" / "README.md").write_text("""# outputs/ — still empty, and it is the one that decides Article 50(2)

A scanner cannot fill this in. Article 50(2) asks whether your **output** is
"marked in a machine-readable format and detectable as artificially generated or
manipulated". That is a property of the file or the HTTP response, not of the
source code — code that calls a C2PA library may still ship an unmarked file.

Generate one real output per modality and paste what these actually print,
including empty output and "no claim found". Absence is the evidence.

```bash
c2patool sample.png                                   # content credentials
exiftool -a -G1 -s sample.png                         # embedded metadata
exiftool -XMP-iptcExt:DigitalSourceType sample.png    # IPTC digital source type
curl -sSI https://your.api/endpoint                   # response headers
```

For generated **text**: the structured data on the rendered page, the API
response envelope and its headers, and any watermark detector you run.

Near-miss to watch for: `"author": {"@type": "Organization"}` marks *who
published*. It does not mark the content as *artificially generated*, and a
machine reading it learns nothing about synthetic origin.

**Without this folder, Article 50(2) can only be `INSUFFICIENT_EVIDENCE`.**
""", encoding="utf-8")

    (pack / "documents" / "README.md").write_text(f"""# documents/

Policy and disclosure files detected in the codebase. Copy in the **rendered,
published** versions — what a user can actually read, not the template.

{chr(10).join('- `' + p + '`' for p in policies) if policies else '_No policy-shaped files found. If you publish a privacy policy or terms, add them here._'}

These corroborate. They rarely decide, and they never substitute for
`first-interaction/`: a disclosure that lives only in a terms document or a
footer has not been provided at the time of first interaction.
""", encoding="utf-8")

    (args.out / "SCAN-NOTES.md").write_text(f"""# Scan notes

`tools/scan_repo.py` read **{n_files} files** under `{root}` and wrote the
evidence pack next to this file.

## What it did

Matched a fixed list of patterns for model-provider calls, generation calls by
modality, provenance-marking libraries, emotion and biometric processing, and
strings that look like AI disclosures. Every hit is cited to `file:line` so you
can check it.

## What it did not do

It did not audit anything, and it did not answer a single question that requires
judgement or knowledge of your business. Specifically it refused: provider versus
deployer, EU availability, the date placed on the market, deep-fake generation,
public-interest publication, editorial responsibility, law-enforcement
authorisation, and SME status.

It also cannot tell you whether your output is actually marked. That needs a
metadata dump from a real generated file — see `evidence-pack/outputs/README.md`.

## Known limits

- Pattern matching. A model call through an unusual wrapper is invisible to it;
  a variable named `watermark` that does nothing will show up as a hit.
- It cannot tell code from prose. A repository that *writes about* AI — docs,
  a blog, marketing copy — will light up every signal it mentions. Check the
  cited lines before believing a row; that is why every hit carries `file:line`.
- Source code is not behaviour. Code that imports a C2PA library may still ship
  unmarked files.
- Nothing here is evidence of what a **user** meets. Article 50 is about what
  reaches a person, and that lives in the rendered product.

## Next

1. Complete every NOT ESTABLISHED row in `evidence-pack/system-facts.md`.
2. Replace `first-interaction/candidates.md` with what a user actually meets first.
3. Fill `outputs/` with a real metadata dump.
4. Hand the pack to the auditor, then verify what comes back:

```bash
python3 tools/verify_citations.py path/to/audit-report.md
```
""", encoding="utf-8")

    print(f"read {n_files} files under {root}")
    print(f"wrote {(args.out).resolve()}")
    print("  evidence-pack/system-facts.md            partly filled, rest marked NOT ESTABLISHED")
    print("  evidence-pack/first-interaction/         candidate disclosure strings, cited")
    print("  evidence-pack/outputs/                   EMPTY — you must supply a metadata dump")
    print("  evidence-pack/documents/                 detected policy files")
    print("  SCAN-NOTES.md                            what was and was not established")
    print("\nThis is a head start, not an audit. Complete it before handing it over.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
